
package webServiceClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiceInterfaceImplService", targetNamespace = "http://ruyanfly/", wsdlLocation = "http://127.0.0.1:8080/WebService?wsdl")
public class ServiceInterfaceImplService
    extends Service
{

    private final static URL SERVICEINTERFACEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICEINTERFACEIMPLSERVICE_EXCEPTION;
    private final static QName SERVICEINTERFACEIMPLSERVICE_QNAME = new QName("http://ruyanfly/", "ServiceInterfaceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8080/WebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICEINTERFACEIMPLSERVICE_WSDL_LOCATION = url;
        SERVICEINTERFACEIMPLSERVICE_EXCEPTION = e;
    }

    public ServiceInterfaceImplService() {
        super(__getWsdlLocation(), SERVICEINTERFACEIMPLSERVICE_QNAME);
    }

    public ServiceInterfaceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICEINTERFACEIMPLSERVICE_QNAME, features);
    }

    public ServiceInterfaceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICEINTERFACEIMPLSERVICE_QNAME);
    }

    public ServiceInterfaceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICEINTERFACEIMPLSERVICE_QNAME, features);
    }

    public ServiceInterfaceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceInterfaceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceInterfaceImpl
     */
    @WebEndpoint(name = "ServiceInterfaceImplPort")
    public ServiceInterfaceImpl getServiceInterfaceImplPort() {
        return super.getPort(new QName("http://ruyanfly/", "ServiceInterfaceImplPort"), ServiceInterfaceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceInterfaceImpl
     */
    @WebEndpoint(name = "ServiceInterfaceImplPort")
    public ServiceInterfaceImpl getServiceInterfaceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ruyanfly/", "ServiceInterfaceImplPort"), ServiceInterfaceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICEINTERFACEIMPLSERVICE_EXCEPTION!= null) {
            throw SERVICEINTERFACEIMPLSERVICE_EXCEPTION;
        }
        return SERVICEINTERFACEIMPLSERVICE_WSDL_LOCATION;
    }

}
